### ISSUE TITLE
Комментарии по задаче

### ISSUE THREAD

**Issue by zhebrak** [python-technopark/match_simulator#1]
Главное замечание — выбор структур данных для хранения статистики.

``` python
            teams[i][4] += a
            teams[i][5] += b
            teams[j][4] += b
            teams[j][5] += a
```

Абсолютно нечитаемый код, невозможно угадать, что скрывается за индексами. Сюда же выбор названий для переменных — a, b, i, j. Если вам, например, понадобится убрать количество ничей из таблицы, вам придется менять все эти магические цифры во всей программе, это плохо. Здесь нужно было использовать словари.

**Comment by Lavifae** [comment]
Спасибо за комментарий, исправим ошибки и учтем на будущее. Мы наконец состоялись как команда, так что в дальнейшем код должен улучшиться :)

**Comment by zhebrak** [comment]
Здорово, что состоялись! Код исправлять необязательно, только если есть большое желание :)
